services:
  - type: web
    name: blog-sds2025
    env: docker
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blog_sds2025_db
          property: connectionString

databases:
  - name: blog_sds2025_db
